### ISSUE TITLE
Convert README to PyPI description?

### ISSUE THREAD

**Issue by katrinleinweber** [edsu/pymarc#117]
https://pypi.org/project/pymarc/#description says: `The author of this package has not provided a project description`. Can this be prevented by displaying [`README.md`'s content](https://github.com/edsu/pymarc#readme) there? Or some of it? Maybe even in a PyPI-standard way?

**Comment by edsu** [comment]
Ok! I was doing this recently for another project.

**Comment by edsu** [comment]
Does this look better? 

https://pypi.org/project/pymarc/

**Comment by edsu** [comment]
Just in case you are curious...

The trick I learned over [here](https://github.com/DocNow/twarc/pull/225) from @hugovk is to pull the markdown in as `long_description` and set `long_description_content_type="text/markdown"` ... then it's necessary to use [twine](https://pypi.org/project/twine/) to do the upload to PyPI instead of `python setup.py upload`.
